image:
  repository: helionys/website
  pullPolicy: IfNotPresent
  tag: dev

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

initContainers:
  init:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: ["/config/init/init.sh"]
    volumeMounts:
      - name: init
        mountPath: "/config/init"
      - name: config
        mountPath: "/config"
