# Default values for ix-chart.

image:
  repository: helionys/website
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

# Restart / Update policy
updateStrategy: RollingUpdate

# Container CMD / entrypoint
containerCommand: []
containerArgs: []
containerEnvironmentVariables: []

# Network related configuration
externalInterfaces: []
portForwardingList: [{"containerPort": 3000, "nodePort": 9080}]
hostPortsList: []
hostNetwork: false
dnsPolicy: Default
dnsConfig:
  nameservers: []
  searches: []

# Storage related configuration
hostPathVolumes: []
volumes: []
emptyDirVolumes: []

# Probes
# Liveness Probe
livenessProbe: null

# Workload type
workloadType: "Deployment"

gpuConfiguration: {}
securityContext:
  privileged: false
  capabilities: []
tty: true
stdin: true
