{{- if and (.Values.portForwardingList) (eq (include "hostNetworkingConfiguration" .) "false") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- range $index, $config := .Values.portForwardingList }}
    - port: {{ $config.containerPort }}
      targetPort: {{ $config.containerPort }}
      protocol: {{ $config.protocol }}
      nodePort: {{ $config.nodePort }}
      name: ix-{{ $.Release.Name }}-{{ $config.nodePort }}-{{ $index }}
    {{- end }}
  selector:
    {{- include "website.selectorLabels" . | nindent 4 }}
{{- end }}
